In [132]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from datetime import datetime

In [106]:
stations = np.array(['FPZ_06A', 'FSB_079', 'FSB_095DR', 'FSB_078', 'FSB_130D',
       'FEX_004', 'FSB_126', 'FPZ_04A', 'FSB_097D', 'FAI_012', 'FAI_009'])

In [138]:
index = 10
df = pd.read_csv(f"../data/merged_data_stationwise/{stations[10]}.csv")
df.head()

,Date Time,station_id,Battery Level (%),Baro (psi),pH (pH),pH MV (mV),ORP (mV),DO (mg/L),% Saturation O₂ (% sat),Partial Pressure O₂ (psi),...,Temperature,Actual Conductivity,Specific Conductivity,Total Dissolved Solids,Pressure,DepthtoWater,Salinity,Resistivity,Density,Depth
0,2022-12-06 18:05:00,FAI_009,76.680870,NaN,7.382824,-22.974014,-223.125931,5.262653,NaN,-0.002578,...,15.006477,301.546173,333.288605,216.637596,0.697054,0.966176,NaN,NaN,NaN,0.681530
1,2022-12-06 19:00:00,FAI_009,76.508575,NaN,7.454239,-27.003288,-218.817703,0.000000,0.0,-0.006563,...,14.182880,298.192535,335.465057,218.052283,0.683507,0.975701,NaN,NaN,NaN,0.671996
2,2022-12-06 20:00:00,FAI_009,76.343117,NaN,7.398293,-23.782253,-211.855881,0.000000,0.0,-0.008276,...,14.030931,300.356476,339.006317,220.354110,0.678645,0.979119,NaN,NaN,NaN,0.668592
3,2022-12-06 21:00:00,FAI_009,76.178192,NaN,7.342291,-20.570755,-204.209808,0.000000,0.0,-0.009286,...,14.008406,302.883942,342.025085,222.316310,0.670778,0.984650,NaN,NaN,NaN,0.663083
4,2022-12-06 22:00:00,FAI_009,76.013260,NaN,7.292656,-17.726421,-198.082443,0.000000,0.0,-0.009885,...,14.014072,304.939301,344.304016,223.797619,0.672280,0.983594,NaN,NaN,NaN,0.664140

In [140]:
df.shape

(9936, 21)

In [142]:
df.isna().sum()

Date Time                       0
station_id                      0
Battery Level (%)               0
Baro (psi)                    893
pH (pH)                       501
pH MV (mV)                    501
ORP (mV)                      494
DO (mg/L)                     501
% Saturation O₂ (% sat)      2239
Partial Pressure O₂ (psi)    4385
External Voltage (V)         3119
Temperature                   497
Actual Conductivity           524
Specific Conductivity         527
Total Dissolved Solids        485
Pressure                      501
DepthtoWater                  487
Salinity                     5303
Resistivity                  3558
Density                      3547
Depth                         493
dtype: int64

In [144]:
df['Date Time'] = df['Date Time'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S').timestamp() * 1000)
df = df.drop('station_id', axis=1)

In [146]:
df.head()

,Date Time,Battery Level (%),Baro (psi),pH (pH),pH MV (mV),ORP (mV),DO (mg/L),% Saturation O₂ (% sat),Partial Pressure O₂ (psi),External Voltage (V),Temperature,Actual Conductivity,Specific Conductivity,Total Dissolved Solids,Pressure,DepthtoWater,Salinity,Resistivity,Density,Depth
0,1.670372e+12,76.680870,NaN,7.382824,-22.974014,-223.125931,5.262653,NaN,-0.002578,NaN,15.006477,301.546173,333.288605,216.637596,0.697054,0.966176,NaN,NaN,NaN,0.681530
1,1.670375e+12,76.508575,NaN,7.454239,-27.003288,-218.817703,0.000000,0.0,-0.006563,NaN,14.182880,298.192535,335.465057,218.052283,0.683507,0.975701,NaN,NaN,NaN,0.671996
2,1.670378e+12,76.343117,NaN,7.398293,-23.782253,-211.855881,0.000000,0.0,-0.008276,NaN,14.030931,300.356476,339.006317,220.354110,0.678645,0.979119,NaN,NaN,NaN,0.668592
3,1.670382e+12,76.178192,NaN,7.342291,-20.570755,-204.209808,0.000000,0.0,-0.009286,NaN,14.008406,302.883942,342.025085,222.316310,0.670778,0.984650,NaN,NaN,NaN,0.663083
4,1.670386e+12,76.013260,NaN,7.292656,-17.726421,-198.082443,0.000000,0.0,-0.009885,NaN,14.014072,304.939301,344.304016,223.797619,0.672280,0.983594,NaN,NaN,NaN,0.664140

In [148]:
column_name = df.columns

In [150]:
num_to_name = {}
for index, val in enumerate(column_name):
    num_to_name[index] = val

In [152]:
imputer = KNNImputer(n_neighbors = 5)
df_imputed_scaled = imputer.fit_transform(df)
df = pd.DataFrame(df_imputed_scaled)

In [154]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.670372e+12,76.680870,14.82595,7.382824,-22.974014,-223.125931,5.262653,0.0,-0.002578,15.5142,15.006477,301.546173,333.288605,216.637596,0.697054,0.966176,0.64183,975.504749,0.999938,0.681530
1,1.670375e+12,76.508575,14.82595,7.454239,-27.003288,-218.817703,0.000000,0.0,-0.006563,15.5142,14.182880,298.192535,335.465057,218.052283,0.683507,0.975701,0.64183,975.504749,0.999938,0.671996
2,1.670378e+12,76.343117,14.82595,7.398293,-23.782253,-211.855881,0.000000,0.0,-0.008276,15.5142,14.030931,300.356476,339.006317,220.354110,0.678645,0.979119,0.64183,975.504749,0.999938,0.668592
3,1.670382e+12,76.178192,14.82595,7.342291,-20.570755,-204.209808,0.000000,0.0,-0.009286,15.5142,14.008406,302.883942,342.025085,222.316310,0.670778,0.984650,0.64183,975.504749,0.999938,0.663083
4,1.670386e+12,76.013260,14.82595,7.292656,-17.726421,-198.082443,0.000000,0.0,-0.009885,15.5142,14.014072,304.939301,344.304016,223.797619,0.672280,0.983594,0.64183,975.504749,0.999938,0.664140

In [156]:
df = df.rename(columns = num_to_name)
df.head()

,Date Time,Battery Level (%),Baro (psi),pH (pH),pH MV (mV),ORP (mV),DO (mg/L),% Saturation O₂ (% sat),Partial Pressure O₂ (psi),External Voltage (V),Temperature,Actual Conductivity,Specific Conductivity,Total Dissolved Solids,Pressure,DepthtoWater,Salinity,Resistivity,Density,Depth
0,1.670372e+12,76.680870,14.82595,7.382824,-22.974014,-223.125931,5.262653,0.0,-0.002578,15.5142,15.006477,301.546173,333.288605,216.637596,0.697054,0.966176,0.64183,975.504749,0.999938,0.681530
1,1.670375e+12,76.508575,14.82595,7.454239,-27.003288,-218.817703,0.000000,0.0,-0.006563,15.5142,14.182880,298.192535,335.465057,218.052283,0.683507,0.975701,0.64183,975.504749,0.999938,0.671996
2,1.670378e+12,76.343117,14.82595,7.398293,-23.782253,-211.855881,0.000000,0.0,-0.008276,15.5142,14.030931,300.356476,339.006317,220.354110,0.678645,0.979119,0.64183,975.504749,0.999938,0.668592
3,1.670382e+12,76.178192,14.82595,7.342291,-20.570755,-204.209808,0.000000,0.0,-0.009286,15.5142,14.008406,302.883942,342.025085,222.316310,0.670778,0.984650,0.64183,975.504749,0.999938,0.663083
4,1.670386e+12,76.013260,14.82595,7.292656,-17.726421,-198.082443,0.000000,0.0,-0.009885,15.5142,14.014072,304.939301,344.304016,223.797619,0.672280,0.983594,0.64183,975.504749,0.999938,0.664140

In [166]:
df.isna().sum()

Date Time                    0
Battery Level (%)            0
Baro (psi)                   0
pH (pH)                      0
pH MV (mV)                   0
ORP (mV)                     0
DO (mg/L)                    0
% Saturation O₂ (% sat)      0
Partial Pressure O₂ (psi)    0
External Voltage (V)         0
Temperature                  0
Actual Conductivity          0
Specific Conductivity        0
Total Dissolved Solids       0
Pressure                     0
DepthtoWater                 0
Salinity                     0
Resistivity                  0
Density                      0
Depth                        0
dtype: int64

In [158]:
df2 = df.copy()
scaler = StandardScaler()
df2[df2.columns] = scaler.fit_transform(df2[df2.columns])

In [160]:
df2.head()

,Date Time,Battery Level (%),Baro (psi),pH (pH),pH MV (mV),ORP (mV),DO (mg/L),% Saturation O₂ (% sat),Partial Pressure O₂ (psi),External Voltage (V),Temperature,Actual Conductivity,Specific Conductivity,Total Dissolved Solids,Pressure,DepthtoWater,Salinity,Resistivity,Density,Depth
0,-2.000684,0.689668,1.785927,0.373182,-0.368533,7.406496,49.738124,0.0,4.623654,-0.706184,-0.499666,-1.665341,-1.861940,-1.861415,1.043432,-1.044274,0.881165,-0.854607,1.225676,1.043693
1,-2.000440,0.680718,1.785927,0.677616,-0.671467,7.552218,-0.014946,0.0,2.873370,-0.706184,-0.688511,-1.675917,-1.854354,-1.853830,0.929704,-0.930471,0.881165,-0.854607,1.225676,0.929841
2,-2.000173,0.672123,1.785927,0.439121,-0.429299,7.787697,-0.014946,0.0,2.120917,-0.706184,-0.723352,-1.669093,-1.842011,-1.841490,0.888888,-0.889627,0.881165,-0.854607,1.225676,0.889196
3,-1.999906,0.663556,1.785927,0.200392,-0.187848,8.046320,-0.014946,0.0,1.677452,-0.706184,-0.728517,-1.661122,-1.831490,-1.830971,0.822845,-0.823540,0.881165,-0.854607,1.225676,0.823407
4,-1.999640,0.654988,1.785927,-0.011194,0.025999,8.253573,-0.014946,0.0,1.414274,-0.706184,-0.727218,-1.654640,-1.823547,-1.823030,0.835455,-0.836158,0.881165,-0.854607,1.225676,0.836036